spring.application.name=hadasim-trip-manager

# conection to SQL SMS-TripDB- using JDBC protocol

spring.datasource.url=jdbc:sqlserver://localhost;databaseName=TripDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=hadasim
spring.datasource.password=123456789


# updating auto the SQL tables according to thr entities, by hibernate
spring.jpa.hibernate.ddl-auto=update

# showing the SQL commmansd in terminal
spring.jpa.show-sql=true